apiVersion: v1
kind: Deployment
metadata:
  name: redis
  tags:
    app: redis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis